### ISSUE TITLE
Endorsing functionality - endorser side

### ISSUE THREAD

**Issue by esune** [bcgov/aries-vcr-issuer-agency#13]
There currently is no way for an `aries-cloudagent` started with endorser capabilities to use `auto` flags to streamline the endorsing process, so implementing a minimal controller is necessary.

The controller will need to expose an endpoint to receive `webhooks` from the endorser agent, and will need to handle the following scenarios:
1. new connection established: once a new connection is established, the endorser needs to set some metadata using the admin api endpoint `​/transactions​/{conn_id}​/set-endorser-role`. The role that must be set is `TRANSACTION_ENDORSER`.
2. once a new transaction requiring endorsing is received, the endorser should just go ahead, endorse it and return it to the author.

Please note that for number `2` it would be wise to design the process so that a manual control could be easily plugged-in if necessary (e.g.: user-controlled gates driven by a web UI)

**Comment by amanji** [comment]
@esune Is there any missing functionality here as described? If so, do we want to open a separate ticket to track those things specifically and close this or should we keep this open?

**Comment by esune** [comment]
> 
> 
> @esune Is there any missing functionality here as described? If so, do we want to open a separate ticket to track those things specifically and close this or should we keep this open?

I think we're good for now. The only thing we did not implement is API endpoints for an admin dashboard, but that should be covered by bcgov/dts-endorser-service#26 I think

**Comment by esune** [comment]
Resolved by bcgov/aries-vcr-issuer-agency#11 when merged
